version: "3.9"
services:
  lime:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - '127.0.0.1:8000:8000'
    hostname: surveyanalyst
    volumes:
      - ./src/limesurvey:/var/www/limesurvey
    environment:
      - APP_KEY=SomeRandomStringToAddSecurity123
      - APP_ENV=development
      - APP_DEBUG=true
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - PORT=8000
    links:
      - pg
    depends_on:
      - pg

  pg:
    build: 
      context: .
      dockerfile: Dockerfile-pg
    hostname: pg
    ports:
       - '127.0.0.1:5432:5432'
